# Generated by Django 3.1.5 on 2021-01-26 07:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authorization.customuser')),
                ('name', models.CharField(max_length=15, verbose_name='中文姓名')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='建立日期')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authorization.customuser')),
                ('name', models.CharField(max_length=15, verbose_name='中文姓名')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='建立日期')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', '顧客'), ('employee', '員工'), ('manager', '管理者'), ('system', '系統'), ('other', '其他User')], default='manager', max_length=20, verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='roler',
            field=models.CharField(choices=[('customer', '顧客'), ('employee', '員工'), ('manager', '管理者'), ('system', '系統'), ('other', '其他User')], default=django.utils.timezone.now, max_length=20, verbose_name='角色'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
