# Generated by Django 3.1.5 on 2021-01-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20210126_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='role',
            field=models.CharField(choices=[('customer', '顧客'), ('employee', '員工'), ('manager', '管理者'), ('system', '系統'), ('other', '其他User')], default='manager', max_length=20, verbose_name='角色'),
        ),
    ]
