# Generated by Django 3.1.5 on 2021-01-27 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_auto_20210127_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='id',
            field=models.IntegerField(auto_created=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='id',
            field=models.IntegerField(auto_created=True),
            preserve_default=False,
        ),
    ]
