# Generated by Django 3.1.5 on 2021-03-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0009_auto_20210224_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', '顧客'), ('employee', '員工'), ('manager', '管理者'), ('system', '系統')], default='manager', max_length=20, verbose_name='角色'),
        ),
    ]
