# Generated by Django 3.1.5 on 2021-03-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0010_auto_20210303_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='datetime',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='datetime',
            new_name='create_at',
        ),
        migrations.AddField(
            model_name='customers',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日期'),
        ),
        migrations.AddField(
            model_name='employees',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日期'),
        ),
    ]
