# Generated by Django 3.1.5 on 2021-03-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0011_auto_20210310_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='id',
            field=models.CharField(default='E2021031000094', max_length=100, unique=True, verbose_name='員工編號'),
        ),
        migrations.AddField(
            model_name='employees',
            name='id',
            field=models.CharField(default='E2021031000011', max_length=100, unique=True, verbose_name='員工編號'),
        ),
    ]
