# Generated by Django 3.1.5 on 2021-03-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0012_auto_20210310_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='id',
            field=models.CharField(default='E202103100007', max_length=100, unique=True, verbose_name='員工編號'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='id',
            field=models.CharField(default='E2021031000041', max_length=100, unique=True, verbose_name='員工編號'),
        ),
    ]
