# Generated by Django 3.1.5 on 2021-03-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0014_auto_20210310_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='id',
            new_name='uuid',
        ),
        migrations.AlterField(
            model_name='customers',
            name='id',
            field=models.CharField(default='E2021031100030', max_length=100, unique=True, verbose_name='員工編號'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='id',
            field=models.CharField(default='E2021031100024', max_length=100, unique=True, verbose_name='員工編號'),
        ),
    ]
