# Generated by Django 3.1.5 on 2021-03-11 13:46

import app.utils.number
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0015_auto_20210311_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='id',
            field=models.CharField(default=functools.partial(app.utils.number.make_user_number, *('C',), **{}), max_length=100, unique=True, verbose_name='員工編號'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='id',
            field=models.CharField(default=functools.partial(app.utils.number.make_user_number, *('E',), **{}), max_length=100, unique=True, verbose_name='員工編號'),
        ),
    ]
